### ISSUE TITLE
could you release vs 1.1.1 to npm?

### ISSUE THREAD

**Issue by shanebdavis** [e-imaxina/cordova-plugin-deeplinks#12]
Vs 1.1.1 fixes an important (blocking) bug, but currently we have to install it manually. Could you push v1.1.1 to NPM? Thank you!

**Comment by juanmiguelbesada** [comment]
I'm so bussy this week. Will try to make a new release the next week.

**Comment by alexcroox** [comment]
Bump, still installing 1.1.0

**Comment by juanmiguelbesada** [comment]
Sorry for the dalay.

Version 1.1.1 should be released to npm.

Thanks for your patience

**Comment by alexcroox** [comment]
Thanks!
