### ISSUE TITLE
App opens with link, but callback isn't fired

### ISSUE THREAD

**Issue by caleb87** [e-imaxina/cordova-plugin-deeplinks#24]
The app will open with a link on Android, but the callback won't trigger. Any ideas?

I used the subscribe after device ready:
`universalLinks.subscribe(null, mycallbackFunction);`

config.xml
```
    <universal-links>
        <ios-team-id value="asdfasdfa" />
        <host name="*.mydomain.com" scheme="https">
            <path url="/limitedPath/*" />
        </host>
    </universal-links>
```

**Comment by caleb87** [comment]
I added the event to the config, and it started working.

<path url="/limitedPath/*" event="eventname" />

**Comment by DanaStefanoska** [comment]
Hello, I'm struggling with the same problem for some time, I'm using angular for this and no matter how I import universal links the subscribe is not firing, can you please add that part of your working solution?
Thank you
