### ISSUE TITLE
Callback does not open the app

### ISSUE THREAD

**Issue by danielpassos** [e-imaxina/cordova-plugin-deeplinks#5]
I'm using an auth service with the `cordova-plugin-deeplinks` but for some reason when the auth service calls my `redirectUri` it opens the URL instead of my app.

Any tip?

**Auth Service callback**
```
redirectUri: 'https://myfakeurl.github.io/login'
```

**config.xml**
```xml
<universal-links>
    <ios-team-id value="myteamid" />
    <host name="myfakeurl.github.io" scheme="https">
        <path event="someevent" url="/login" />
    </host>
</universal-links>
```

**Comment by noxiousmobile** [comment]
How and where do you call the event name someevent?
