### ISSUE TITLE
Deeplinking not working with iOS?

### ISSUE THREAD

**Issue by JimmyMultani** [e-imaxina/cordova-plugin-deeplinks#6]
For some reason, I can't seem to get iOS to open my app when clicking on a link that matches the host, in Gmail or Safari. I have the `apple-app-site-association` file in the root directory of my website, but it doesn't seem to be triggering anything.

This setup works perfectly fine in Android though.

Any help would be greatly appreciated.

**config.xml**
```xml
<universal-links>
        <ios-team-id value="<TEAM_ID>" />
        <host event="ul_deepLink" name="*.something.com" scheme="https" />
</universal-links>
```
**apple-app-site-association**
```json
{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "<TEAM_ID>.com.something.app",
        "paths": ["*"]
      }
    ]
  }
}
```

**Comment by contactfoaix** [comment]
The solution is to make sure the Entitlements-Debug.plist and Entitlements-Release.plist has the lines:
`<key>com.apple.developer.associated-domains</key>
    <array>
      <string>applinks:domainname.com</string>
    </array>`

All actual host names of each environment should be list within the <array> wrap by <string> tag. The applinks doesn't recognize the format of "*.domainname.com" referring various subdomain environments.

**Comment by JimmyMultani** [comment]
Yup, that was the issue! Thanks @contactfoaix!
